version: "3.7"
services:
  pgadmin4:
    image: dpage/pgadmin4:4.25
    environment:
      PGADMIN_DEFAULT_EMAIL: shahjalal.tipu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8888:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
    networks:
      - dbnet

volumes:
  pgadmin4:

networks:
  dbnet:
    driver: bridge
